development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: project_17_development
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: project_17_test
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
